Add attached functions for v5.
IronCoreLabs/ironcore-documents pull request #11
Opened 2023-12-14 01:46 UTC by coltfred

Added functions and types for dealing with v5 attached documents.

2023-12-14 16:46 UTC, giarc3 requested changes
Mostly just style/comment suggestions

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +            &edoc.0, // Note that the edoc is written without a header since it's an attached document.
By "without a header" do you mean "0IRON"? It's a bit confusing because this does have a V4DocumentHeader right before it.

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +pub fn encode_attached_edoc(
It feels like this could just be a function on `AttachedDocument` with an "into bytes" type of name

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +pub fn decode_attached_edoc(b: Bytes) -> Result<AttachedDocument> {
Similarly, this feels like a TryInto from Bytes to AttachedDocument

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +        let len = attached_document_with_header.get_u16();
1. Maybe `header_len` as a name to indicate that it's just the V4DocumentHeader length
2. Can you comment here that this advances the byte buffer by 2 bytes? I forgot that and was confused for a bit (or byte)

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +                edoc: IvAndCiphertext(attached_document_with_header),
Sad that the name `attached_document_with_header` is not true when it gets here, but it is what it is.

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +            Err(Error::HeaderParseErr("Edek length too long.".to_string()))
I would read this error to mean "the EDEK you passed in was too long", but it's meant as "The EDEK you passed in was too short based on the length bytes". Obviously mine is too wordy, but maybe some wordsmithing to clarify

2023-12-14 16:46 UTC, giarc3 commented on src/v5/attached.rs
> +        Err(Error::HeaderLengthOverflow(encoded_edek.len() as u64))
I don't think I did this check in other modules...

2023-12-18 15:18 UTC, coltfred commented on src/v5/attached.rs
> +pub fn encode_attached_edoc(
I did this because it mirrors how the v4 documents module is setup, but I did move it and we can see how it feels.

2023-12-18 15:18 UTC, coltfred commented on src/v5/attached.rs
> +        Err(Error::HeaderLengthOverflow(encoded_edek.len() as u64))
It's checked in v4 attached and v5 attached. Those are the only 2 that use this style format so I think it's ok. What other place did you think we should check this?

2023-12-18 15:18 UTC, coltfred commented on src/v5/attached.rs
> +            &edoc.0, // Note that the edoc is written without a header since it's an attached document.
Updated the comment.

2023-12-18 15:18 UTC, coltfred commented on src/v5/attached.rs
> +pub fn decode_attached_edoc(b: Bytes) -> Result<AttachedDocument> {
👍

2023-12-18 15:18 UTC, coltfred commented on src/v5/attached.rs
> +        let len = attached_document_with_header.get_u16();
I chose `edek_len`. Lmk if you think that's better.

2023-12-18 15:18 UTC, coltfred commented on src/v5/attached.rs
> +            Err(Error::HeaderParseErr("Edek length too long.".to_string()))
I don't think it's too long.

2023-12-18 17:56 UTC, giarc3 approved these changes

2023-12-18 21:08 UTC, merged