Changes to error types and moved some functions into modules
IronCoreLabs/ironcore-documents pull request #13
Opened 2024-01-08 18:03 UTC by giarc3

- Stopped directly wrapping crypto error messages (like `aead::Error`) for our own errors
- Changes the Display impls for each error to be more verbose/human-readable
- Moved functions from lib.rs into their respective modules (I think they were all v4-related functions)
- Made some functions non-pub, as we don't call them externally, hopefully making our API surface easier to understand next time we visit this repo

2024-01-08 21:15 UTC, coltfred requested changes
One concern about an error.

2024-01-08 21:15 UTC, coltfred commented on src/aes.rs
> +                "Decryption failed. Check the data and tenant ID are correct".to_string(),
The reason you mention tenant here is because where we're using it that's how keys are fetched/derived. In the case of IronCore Documents it's be key and data. We will need to remap this error type in places we use it where the caller thinks of the key as being mapped from the tenant.

2024-01-08 23:28 UTC, giarc3 commented on src/aes.rs
> +                "Decryption failed. Check the data and tenant ID are correct".to_string(),
Changed to "Ensure the data and key are correct."

2024-01-09 03:07 UTC, coltfred approved these changes

2024-01-09 15:51 UTC, merged