Split code into modules based on the version of edoc/edek they're used for
IronCoreLabs/ironcore-documents pull request #9
Opened 2023-12-08 21:51 UTC by coltfred

This diff is especially messy because I broke code into so many different modules. I'll try to describe my logic so we can tell in the future why things are the way they are.

Things at the top level have to do with the V4DocumentHeader. Creating it, signing it, etc.

`v4` - Contains things to do with v4 specific things. This has a bunch of attached code in it currently, which isn't being used by ironcore-alloy, but a PR is incoming once the dust settles.
`v5` - `key_id_header`, `EncryptedPayload`.
`v3` - Specific things for v3 edoc and edek.

2023-12-08 23:03 UTC, giarc3 requested changes
I reviewed it all, but it's still a jumble in my head. I'll keep reading through it to try to come up with further suggestions

2023-12-08 23:03 UTC, giarc3 commented on src/aes.rs
> +// This module is dedicated with things to do with oes encryption/decryption.
```suggestion
// This module is dedicated with things to do with aes encryption/decryption.
```

2023-12-08 23:03 UTC, giarc3 commented on src/aes.rs
> +        IvAndCiphertext([].as_ref().into())
```suggestion
        IvAndCiphertext(Bytes::new())
```

2023-12-08 23:03 UTC, giarc3 commented on src/aes.rs
>  ) -> std::result::Result<PlaintextDocument, Error> {
```suggestion
) -> Result<PlaintextDocument> {
```

2023-12-08 23:03 UTC, giarc3 commented on src/v3/mod.rs
> +const MAGIC: &[u8; 4] = crate::v4::MAGIC;
How come this instead of the import?

2023-12-08 23:03 UTC, giarc3 commented on src/aes.rs
> +    aes_encrypted_payload: &[u8],
Should this take IvAndCiphertext now?

2023-12-08 23:03 UTC, giarc3 commented on src/v3/mod.rs
> +            decrypt_document_with_attached_iv(key, &self.iv_and_ciphertext)
(Can't comment the above line)
Should `self.iv_and_ciphertext` be an `IvAndCiphertext` now?

2023-12-08 23:03 UTC, giarc3 commented on src/v4/attached.rs
> +                .filter(|bytes| *bytes == MAGIC[..])
```suggestion
                .filter(|bytes| bytes.as_ref() == MAGIC)
```

2023-12-08 23:03 UTC, giarc3 commented on src/v4/attached.rs
> +                let rest = b.split_off(header_size);
I would keep using `split_to` and then the header can have a meaningful name

2023-12-08 23:03 UTC, giarc3 commented on src/v5/mod.rs
> +        result
Is this better than chaining?

2023-12-08 23:03 UTC, giarc3 commented on src/v5/mod.rs
> +pub struct EncryptedPayload(pub IvAndCiphertext);
This inner type seems wrong, since it also have the 0IRON

2023-12-11 20:10 UTC, coltfred commented on src/v5/mod.rs
> +        result
It guarantees that we won't have to resize the vec at all. This seems better in the case that we know the exact length.

2023-12-11 20:10 UTC, coltfred commented on src/v4/attached.rs
> +                let rest = b.split_off(header_size);
Sure. I don't have attachment either way.

2023-12-11 20:12 UTC, giarc3 approved these changes

2023-12-11 21:27 UTC, merged